### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by dostrander** [Raizlabs/RZBluetooth#19]
It'd be nice to have OSX support especially for the Mock framework so we can have the a simulator and a command line peripheral/central at the same time.

**Comment by samdmarshall** [comment]
I opened a pull request for this, #31. This doesn't explicitly add support to the Mocking framework, but it did work for my needs of being able to do some work with an OS X app.

**Comment by KingOfBrian** [comment]
Sweet, thanks @samdmarshall!
