### ISSUE TITLE
Swift support in RZBPeripheralConnectionDelegate

### ISSUE THREAD

**Issue by cpatterson-lilly** [Raizlabs/RZBluetooth#27]
Just migrated my code to 1.0, and ran into this issue.

The declaration of the `RZBPeripheralConnectionDelegate` protocol method:

`- (void)peripheral:(RZBPeripheral *)peripheral connectionEvent:(RZBPeripheralStateEvent)event error:(NSError *)error;`

...needs the error parameter to be `__nullable` to work properly with Swift. Currently, since the error parameter is not `Optional` in Swift, it will cause a crash if the error is null.

For now, I'm working around the issue by declaring my implementation of the delegate method with an `NSError?` parameter, but that generates a build warning.

**Comment by KingOfBrian** [comment]
Ahh good catch, sorry about that. I just pushed up 1.0.1. It's hard to fully test the swift API without re-writing all the tests in swift. I have the start of some swift tests, but they're far from extensive.


Brian
