### ISSUE TITLE
((self.centralManager.dispatch.commands.count == 0) is true) failed - Expected 0 commands, saw 1

### ISSUE THREAD

**Issue by drdaz** [Raizlabs/RZBluetooth#30]
I'm getting this assertion failure in my tests; it seems to be timing related. In tests that execute and finish very quickly it appears. In longer running tests, less so.

**Comment by KingOfBrian** [comment]
You probably need to `waitForQueueFlush` at the end of your test -- or do something to wait for whatever asynchronous operation you've done to complete. If it's still a problem, can you upload a log file?

Thanks!

**Comment by drdaz** [comment]
`waitForQueueFlush` does the trick. Thanks!
