### ISSUE TITLE
Crash in RZBPeripheral -clearNotifyBlockForCharacteristicUUID:serviceUUID:completion:

### ISSUE THREAD

**Issue by cpatterson** [Raizlabs/RZBluetooth#32]
If an invalid characteristicUUID parameter is passed to the above method, the app will crash because the underlying method -setNotifyBlock:forCharacteristicUUID: is passed a nil UUID which it tries to use as a key in the notifyBlocks dictionary.

This can happen if an app tries to clear notify blocks (ie. unregister notification/indication observers) immediately in response to a peripheral disconnection.

Pull request coming soon...

**Comment by KingOfBrian** [comment]
Hey @cpatterson -- thanks for the issue and PR. Just getting a chance to read through things now.
