### ISSUE TITLE
Convert to CBManagerState for iOS 10.

### ISSUE THREAD

**Issue by cpatterson** [Raizlabs/RZBluetooth#34]
In the iOS 10 SDK, they've combined CBCentralManagerState and CBPeripheralManagerState into one type called CBManagerState.

Currently, building RZBluetooth in Xcode 8/iOS 10 SDK throws warnings about the type conversion:

`warning: implicit conversion from enumeration type 'CBManagerState' (aka 'enum CBManagerState') to different enumeration type 'CBCentralManagerState' (aka 'enum CBCentralManagerState') [-Wenum-conversion]`

**Comment by cpatterson-lilly** [comment]
Just updated to RZBluetooth version 1.1.1; I'm still seeing some build warnings related to CBManagerState caused by RZBErrors.h and RZBMockPeripheralManager.h.

**Comment by KingOfBrian** [comment]
Looks like I missed the `state` property in `RZBMockPeripheralManager.h`. 

I'm really confused why I'm not getting any deprecation warnings when I build the project. Do you not get any errors in `RZBCentralManager.m` @cpatterson ?

**Comment by cpatterson-lilly** [comment]
No errors, only build warnings. 

Note that I'm building a framework using CocoaPods, that adds RZBluetooth as a dependency in its own Podfile. It also uses Mock and Test. Here's my framework's Podfile:
```
# Defines a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'MyFramework' do
    pod 'RZBluetooth',      '~> 1.1'
    pod 'RZBluetooth/Mock', '~> 1.1'
end

target 'MyFrameworkTests' do
    pod 'RZBluetooth',      '~> 1.1'
    pod 'RZBluetooth/Mock', '~> 1.1'
    pod 'RZBluetooth/Test', '~> 1.1'
end
```

I've not yet attempted to build my app that includes my framework yet. If errors pop up at that point I'll let you know.

**Comment by KingOfBrian** [comment]
Can you point to `bugfix/iOS10DefineChanges` real quick and double check that it's error free? I should be able to push up a fix pretty quick

**Comment by cpatterson-lilly** [comment]
That did the trick.
