### ISSUE TITLE
API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported

### ISSUE THREAD

**Issue by drdaz** [Raizlabs/RZBluetooth#35]
I just updated to Xcode 8, and I'm now seeing the following warning:

"API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported"

I'm not sure how dangerous this is; I'm guessing the issue was there the whole time but I wasn't seeing the warning. Thought you should know about it though.

**Comment by KingOfBrian** [comment]
Hey @drdaz -- Thanks for the heads up. If you specify `bluetooth-central` in `UIBackgroundModes`, this warning should go away. If you could double check that this resolves your issue, I'll add a note to the README.
