### ISSUE TITLE
Manually prompt discovery of characteristics?

### ISSUE THREAD

**Issue by drdaz** [Raizlabs/RZBluetooth#5]
Hey there

Is there some way of manually making characteristic discovery happen? I have a write characteristic that I'd like to have discovered before I write to it...

And a hacky solution is fine, because I'm writing a hack.

**Comment by KingOfBrian** [comment]
Hey @drdaz -- I made a branch with an implementation of manual characteristic discovery. Can you try it out? I haven't been able to add a test for it, but it should "Just Work" :tm:

Thanks!

**Comment by drdaz** [comment]
Oh wow thanks :)

I'll try merging that into my fork asap.

**Comment by drdaz** [comment]
Hey! Just an FYI. I've been using this patch for a few weeks now. Seems to Just Work.

**Comment by KingOfBrian** [comment]
I merged in the fix, so I'm closing this out.
