### ISSUE TITLE
RZBPeripheral and RZBSimulatedDevice cannot handle same characteristic UUID on multiple services

### ISSUE THREAD

**Issue by cpatterson-lilly** [Raizlabs/RZBluetooth#64]
### Issue
The `RZBSimulatedDevice` class cannot handle the case where a device implements 2 or more services that share a common characteristic UUID. If you try to add a read/write/subscribe handler for the duplicate characteristic UUID, obviously, it overwrites the previous one added.

The internal `readHandlers`, `writeHandlers`, and `subscribeHandlers` dictionaries use only the characteristic UUID as the key; they should use a combination of characteristic UUID and service UUID (or an `RZBUUIDPath`).

Similarly, the corresponding `{add|remove}{Read|Write|Subscribe}CallbackForCharacteristicUUID:handler:` methods should be modified to take an additional service UUID parameter (or replace them with an `RZBUUIDPath` parameter).

This is probably not a common use case, but it can happen, for instance, if a device implements a [Record Access Control Point](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.record_access_control_point.xml) for 2 different kinds of data records on separate services.

**Comment by cpatterson-lilly** [comment]
Just sent a PR to fix this one.

**Comment by cpatterson-lilly** [comment]
Just discovered that `RZBPeripheral` has a similar problem with its `notifyBlocksByUUID` dictionary. This also needs to differentiate characteristics with the same UUID on different services.

**Comment by KingOfBrian** [comment]
Ouch, good catch. I'll move any remaining feedback to the PR, but at a high level:
- I'd like to keep RZBUUIDPath private
- I'd like to maintain compatibility, so I'd prefer to have the `{add|remove}{Read|Write|Subscribe}CallbackForCharacteristicUUID:handler:` methods still function.
