### ISSUE TITLE
Occasional crash in RZBPeripheralState

### ISSUE THREAD

**Issue by drdaz** [Raizlabs/RZBluetooth#7]
I've crashed a few times here. I can't tell you what I've done to cause it; it seems very random. I've attached a screenshot.
![screen shot 2016-01-15 at 14 47 06](https://cloud.githubusercontent.com/assets/845731/12354555/1b206840-bb97-11e5-85fc-4803698fb56e.png)

**Comment by mr-fixit** [comment]
![image](https://cloud.githubusercontent.com/assets/325572/12354863/c855821a-bb66-11e5-9d8a-63486abbb438.png)

**Comment by KingOfBrian** [comment]
Hey @drdaz , Looks like an error cased the characteristic to be nil and assert. I added a commit to the other PR which should address the issue. 

Good catch!
