### ISSUE TITLE
Mocking cannot be enabled and disabled on demand

### ISSUE THREAD

**Issue by mplorentz** [Raizlabs/RZBluetooth#82]
### Issue

Enabling and disabling RZBluetooth mocking is not working as I expect. 

Steps to reproduce:
1. Enable mocking (`RZBEnableMock(true)`)
2. Disable mocking (`RZBEnableMock(false)`)
3. Enable mocking (`RZBEnableMock(true)`)
4. Instantiate a `CBPeripheralManager`

Expected: `CBPeripheralManager.mock` is not nil.
Actual: `CBPeripheralManager.mock` is nil.

### Example
I've attached and example project. It is a mixed Objective-C/Swift framework project since that is how my current project is set up. You can demonstrate the issue by running the tests.
[RZBDisableMockExample.zip](https://github.com/Raizlabs/RZBluetooth/files/1647058/RZBDisableMockExample.zip)

**Comment by cpatterson-lilly** [comment]
Hmmm. This might be related to using `method_exchangeImplementations` for swizzling the `alloc` methods.

See these articles:
https://blog.newrelic.com/2014/04/16/right-way-to-swizzle/
http://petersteinberger.com/blog/2014/a-story-about-swizzling-the-right-way-and-touch-forwarding/
