### ISSUE TITLE
Crash in -[RZBPeripheral clearNotifyBlocks]

### ISSUE THREAD

**Issue by joshuatbrown** [Raizlabs/RZBluetooth#96]
### Issue
The `clearNotifyBlocks` method in `RZBPeripheral` crashes when there's at least one key/value pair in the `self.notifyBlockByUUIDs` `NSMutableDictionary`.

The reason is that `clearNotifyBlocks` iterates over the `self.notifyBlockByUUIDs` dictionary, calling `clearNotifyBlockForKey:`. In `clearNotifyBlockForKey:`, the key/value pair is removed from `self.notifyBlockByUUIDs`. This crashes since we're removing an object from the dictionary we're currently iterating over. Here's the error message:

```
Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x7f9f31a84440> was mutated while being enumerated.'
```

The fix is straightforward and just requires a small change to `clearNotifyBlocks`:

```objc
- (void)clearNotifyBlocks {
    NSArray *keys = self.notifyBlockByUUIDs.allKeys;
    for (NSString* key in keys) {
        [self clearNotifyBlockForKey:key];
    }
}
```

I have this fixed locally and may be able to create a PR soon, but I wanted to document the problem and solution just in case I don't get to it right away.

**Comment by chrisballinger** [comment]
Thanks!

**Comment by iowlit** [comment]
I faced with the same crash. Please merge the pull request.
